---
- name: Development Environment Setup
  hosts: all
  vars_files:
    - vars.yml

  tasks:
    - name: Basic Setup
      sudo: true
      dnf: name={{ item }} state=latest
      with_items:
        - git

